const CONFIG = {
  SERVER_URL: "https://tonton-kondo-lry5.onrender.com",
  FOOTBALL_API_KEY: "369f772ca235e44f4d4b743c2df1cac8",
  ADMIN_PASSWORD: "admin",
  SECRET_STAFF_CODE: "TONTONKONDO12",
  SESSION_DURATION_DAYS: 7,
  JACKPOT_PERCENT: 5,
};
